server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haya152-nga?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #druid数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  thymeleaf:
    prefix=classpath:/templates/

mybatis:
  # 扫描包, 自动配置别名
  type-aliases-package: com.fclProject.haya152.producer.nga.dto
  # 配置mapper.xml路径
  mapper-locations: classpath:mybatis/mapper/NgaMapper.xml

logging:
  level:
    com: off

nga:
  building: nga06
  url: https://bbs.nga.cn/read.php?tid=30226559
#  url: https://bbs.nga.cn/read.php?tid=29593236
  cookieName: "bbsmisccookies"
  cookieValue: "%7B%22uisetting%22%3A%7B0%3A1%2C1%3A1642593567%7D%2C%22pv_count_for_insad%22%3A%7B0%3A-110%2C1%3A1642525230%7D%2C%22insad_views%22%3A%7B0%3A2%2C1%3A1642525230%7D%7D; taihe=c657c4764193245afe9a430f73f93e78; lastvisit=1642490788; ngaPassportUid=61692441; lastpath=/read.php?tid=30226559&page=1131; ngacn0comUserInfo=FlowingCloudL%09FlowingCloudL%0939%0939%09%0910%09100%094%090%090%09130_10%2C61_1; ngacn0comUserInfoCheck=54c59300b7577ce46ec0132d4131d98d; ngacn0comInfoCheckTime=1642487646; ngaPassportUrlencodedUname=FlowingCloudL; ngaPassportCid=X8u0sts3vbo49j5qit38cbrerte6af3cf2136scg"